name: 'Setup Node.js with Cache'
description: 'Setup Node.js and cache dependencies'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      shell: bash